spring:
  application:
    name: camel-gateway

server:
  port: 8081

gateway:
  proxy:
    host: 0.0.0.0
    port: 8082
  environment: local

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true

camel:
  main:
    name: camel-gateway
    run-controller: true
