insert into gateway_ops.audit_events (
    correlation_id,
    consumer_id,
    service_id,
    http_method,
    request_path,
    response_code,
    elapsed_ms,
    error_code,
    authorized,
    rate_limited,
    client_ip,
    user_agent,
    backend_endpoint,
    request_size,
    response_size,
    created_at
) values (
    coalesce(:#AuditCorrelationId, 'unknown'),
    :#AuditConsumerId,
    coalesce(:#AuditServiceId, 'unknown-service'),
    coalesce(:#AuditMethod, 'UNKNOWN'),
    coalesce(:#AuditPath, 'UNKNOWN'),
    :#AuditResponseCode,
    :#AuditElapsedMs,
    :#AuditErrorCode,
    :#AuditAuthorized,
    :#AuditRateLimited,
    :#AuditClientIp,
    :#AuditUserAgent,
    :#AuditBackendEndpoint,
    :#AuditRequestSize,
    :#AuditResponseSize,
    current_timestamp
)
